[package]
name = "rshash"
version = "0.1.0"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2018"
description = "A utility for computing various message digests"
readme = "README.adoc"
repository = "https://github.com/sorairolake/rshash"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
blake2 = "0.9.1"
blake3 = "0.3.8"
const_format = "0.2.14"
directories = "3.0.2"
gost94 = "0.9.1"
groestl = "0.9.0"
hex = "0.4.3"
indexmap = "1.6.2"
md-5 = "0.9.1"
md2 = "0.9.0"
md4 = "0.9.0"
ripemd160 = "0.9.1"
ripemd320 = "0.9.0"
serde = { version = "1.0.126", features = ["derive"] }
sha-1 = "0.9.6"
sha2 = "0.9.5"
sha3 = "0.9.1"
shabal = "0.3.0"
streebog = "0.9.2"
structopt = "0.3.21"
tiger = "0.1.0"
toml = "0.5.8"
whirlpool = "0.9.0"

[features]
# For assembly implementation.
md5-asm = ["md-5/asm"]
sha1-asm = ["sha-1/asm"]
sha2-asm = ["sha2/asm"]
whirlpool-asm = ["whirlpool/asm"]
asm = ["md5-asm", "sha1-asm", "sha2-asm", "whirlpool-asm"]

# For BLAKE3 optimization.
blake3-neon = ["blake3/neon"]
blake3-rayon = ["blake3/rayon"]

[profile.release]
lto = true
