[package]
name = "rshash"
version = "0.1.0"
authors = ["Shun Sakai <sorairolake@protonmail.ch>"]
edition = "2018"
description = "A utility for computing various message digests"
readme = "README.adoc"
repository = "https://github.com/sorairolake/rshash"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
