= RSHash
:toc:

*RSHash* is a command-line utility for computing and checking various message digests.

== Installation

=== How to build and install

Please refer to the link:INSTALL.adoc[Installation Guide].

== Usage

....
RSHash 0.1.0
A utility for computing various message digests

USAGE:
    rshash [FLAGS] [OPTIONS] [FILE]...

FLAGS:
    -c, --check                   Read the checksums from the file and check them
    -h, --help                    Prints help information
        --list-hash-algorithms    List supported hash algorithms
        --quiet                   Don't print OK for each successfully verified file
        --status                  Don't output anything, return the verification result as the exit status
    -V, --version                 Prints version information

OPTIONS:
    -H, --hash-algorithm <NAME>    Specify hash algorithm [possible values: blake2b, blake2s, blake3, gost, gost-
                                   cryptopro, groestl-224, groestl-256, groestl-384, groestl-512, keccak-224,
                                   keccak-256, keccak-384, keccak-512, md2, md4, md5, ripemd-160, ripemd-320, sha1,
                                   sha224, sha256, sha384, sha512, sha3-224, sha3-256, sha3-384, sha3-512, shabal-192,
                                   shabal-224, shabal-256, shabal-384, shabal-512, streebog-256, streebog-512, tiger,
                                   whirlpool]
    -o, --output <FILE>            Output to <FILE> instead of stdout
        --style <STYLE>            Specify style of the checksums [default: SFV]  [possible values: sfv, bsd]

ARGS:
    <FILE>...    Input from <FILE>
....

See the link:doc/man/man1/rshash.1.adoc[man page] (`man 1 rshash`) for details.

== Configuration

If you want to change the default behavior, you can use the configuration file.

See the link:doc/man/man5/rshash-config.toml.5.adoc[man page] (`man 5 rshash-config.toml`) for details.

== Contributing

Please refer to the link:CONTRIBUTING.adoc[Contribution Guide].

== License

Copyright (C) 2021 Shun Sakai (see link:AUTHORS.adoc[])

This program is distributed under the terms of the _GNU General Public License v3.0 or later_.

See link:COPYING[] for details.
