//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Copyright (C) 2021 Shun Sakai
//

= rshash(1)
// Specify in UTC.
:docdate: 2022-04-19
:doctype: manpage
ifdef::revnumber[:mansource: RSHash {revnumber}]
:manmanual: General Commands Manual
:includedir: ../include

== NAME

rshash - a utility for computing various message digests

== SYNOPSIS

*{manname}* [_OPTION_]... [_FILE_]...

== DESCRIPTION

*RSHash* is a command-line utility for computing and checking various message
digests.
If _FILE_ is not specified, the input is read from stdin.

== OPTIONS

Unless otherwise noted, the value of each option is case-insensitive.

=== Hash algorithms options

*-H*, *--hash-algorithm* _NAME_::
  Specify hash algorithm.

  Possible values for this option are:{blank}:::

    * *blake2b* and *blake2s* (BLAKE2)
    * *blake3* (BLAKE3)
    * *fsb160*, *fsb224*, *fsb256*, *fsb384* and *fsb512* (FSB)
ifdef::gost94[]
    * *gost* and *gost-crypto-pro* (GOST)
endif::[]
    * *groestl224*, *groestl256*, *groestl384* and *groestl512* (Groestl)
    * *keccak224*, *keccak256*, *keccak384* and *keccak512* (Keccak)
ifdef::md2[]
    * *md2* (MD2)
endif::[]
ifdef::md4[]
    * *md4* (MD4)
endif::[]
ifdef::md-5[]
    * *md5* (MD5)
endif::[]
    * *ripemd160*, *ripemd256* and *ripemd320* (RIPEMD)
ifdef::sha-1[]
    * *sha1* (SHA-1)
endif::[]
    * *sha224*, *sha256*, *sha384* and *sha512* (SHA-2)
    * *sha3-224*, *sha3-256*, *sha3-384* and *sha3-512* (SHA-3)
    * *shabal192*, *shabal224*, *shabal256*, *shabal384* and *shabal512*
      (Shabal)
    * *sm3* (SM3)
ifdef::streebog[]
    * *streebog256* and *streebog512* (Streebog)
endif::[]
    * *tiger* (Tiger)
    * *whirlpool* (Whirlpool)

*--list-hash-algorithms*::
  List supported hash algorithms.

=== Verification options

*-c*, *--check*::
  Read the checksums from the file and check them.

*--ignore-missing*::
  Don't fail or report status for missing files.

*--quiet*::
  Don't print OK for each successfully verified file.

*--status*::
  Don't output anything, return the verification result as the exit status.

*--strict*::
  Exit non-zero for improperly formatted checksum lines.

*-w*, *--warn*::
  Warn about improperly formatted checksum lines.

*-j*, *--json*::
  Output the verification result as JSON to stdout.
  If you want to pretty-printing, specify *--pretty* as well.

*-p*, *--pretty*::
  Output as a pretty-printed JSON.

=== I/O options

*-o*, *--output* _FILE_::
  Output to _FILE_ instead of stdout.

*-s*, *--style* _FORMAT_::
  Specify style of the checksums.
  If this option is not specified, it is the same as selecting the default
  value.

  Possible values for this option are:{blank}:::

    * *sfv* (SFV output format, default)
    * *bsd* (BSD output format)
    * *json* (JSON output format)

=== General options

*-T*, *--threads* _NUM_::
  Specify the number of threads to use.
  If _NUM_ is *0*, use as many threads as there are CPU cores.
  Default is *0*.

*--progress*::
  Display a progress bar for reporting progress.

*--speed*::
  Print the processing speed.

*-h*, *--help*::
  Print help message and exit.

*-V*, *--version*::
  Print the version number and exit.

*--generate-completion* _SHELL_::
  Generate shell completion.
  The generated shell completion is output to stdout.
  To output as a shell completion file, specify the directory to store using
  *--output* _OUT_DIR_.

  Possible values for this option are:{blank}:::

    * *bash* (Bash)
    * *elvish* (Elvish)
    * *fish* (fish)
    * *powershell* (PowerShell)
    * *zsh* (Zsh)

== EXIT STATUS

If successful, return 0 as the exit status.
Otherwise, return non-zero as the exit status.

== EXAMPLES

Compute BLAKE2b message digest:{blank}::
  $ *{manname} -H blake2b input.txt*

include::{includedir}/section-reporting-bugs.adoc[]

include::{includedir}/section-copyright.adoc[]

== SEE ALSO

*md5sum*(1), *rhash*(1), *rshash-config.toml*(5)
